version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade aws-sam-cli
      - pip install -r requirements.txt || true

  build:
    commands:
      - echo "Running SAM build"
      - sam build

  post_build:
    commands:
      - echo "Packaging Lambda"
      - cd .aws-sam/build/MyLambdaFunction
      - zip -r ../../function.zip .

artifacts:
  files:
    - function.zip
