version: 0.2

phases:
  install:
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
      - zip -r function.zip .aws-sam/build/LambdaFunctionForPipeline  # Replace MyFunction with your Lambda logical ID

artifacts:
  files:
    - function.zip
