version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade aws-sam-cli
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found"; fi

  build:
    commands:
      - echo "Running SAM build"
      - sam build

  post_build:
    commands:
      - echo "Packaging Lambda"
      - cd .aws-sam/build/PipelineLambdaFunction
      - zip -r ../../function.zip .

artifacts:
  files:
    - function.zip
